// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: patient.proto
// Protobuf Java Version: 4.34.1

package com.kenyajug.encounter.grpc.patient;

@com.google.protobuf.Generated
public final class PatientOuterClass extends com.google.protobuf.GeneratedFile {
  private PatientOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PatientOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PatientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patient.Patient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string dob = 3;</code>
     * @return The dob.
     */
    java.lang.String getDob();
    /**
     * <code>string dob = 3;</code>
     * @return The bytes for dob.
     */
    com.google.protobuf.ByteString
        getDobBytes();
  }
  /**
   * Protobuf type {@code patient.Patient}
   */
  public static final class Patient extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:patient.Patient)
      PatientOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "Patient");
    }
    // Use Patient.newBuilder() to construct.
    private Patient(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Patient() {
      uuid_ = "";
      name_ = "";
      dob_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_Patient_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_Patient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_Patient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.class, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dob_ = "";
    /**
     * <code>string dob = 3;</code>
     * @return The dob.
     */
    @java.lang.Override
    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dob_ = s;
        return s;
      }
    }
    /**
     * <code>string dob = 3;</code>
     * @return The bytes for dob.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dob_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, dob_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dob_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, dob_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient)) {
        return super.equals(obj);
      }
      com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient other = (com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getDob()
          .equals(other.getDob())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOB_FIELD_NUMBER;
      hash = (53 * hash) + getDob().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patient.Patient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patient.Patient)
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_Patient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_Patient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.class, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder.class);
      }

      // Construct using com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uuid_ = "";
        name_ = "";
        dob_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_Patient_descriptor;
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient getDefaultInstanceForType() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.getDefaultInstance();
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient build() {
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient buildPartial() {
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient result = new com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uuid_ = uuid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dob_ = dob_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient) {
          return mergeFrom((com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient other) {
        if (other == com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDob().isEmpty()) {
          dob_ = other.dob_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                dob_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object dob_ = "";
      /**
       * <code>string dob = 3;</code>
       * @return The dob.
       */
      public java.lang.String getDob() {
        java.lang.Object ref = dob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dob_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dob = 3;</code>
       * @return The bytes for dob.
       */
      public com.google.protobuf.ByteString
          getDobBytes() {
        java.lang.Object ref = dob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dob = 3;</code>
       * @param value The dob to set.
       * @return This builder for chaining.
       */
      public Builder setDob(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dob_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string dob = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDob() {
        dob_ = getDefaultInstance().getDob();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string dob = 3;</code>
       * @param value The bytes for dob to set.
       * @return This builder for chaining.
       */
      public Builder setDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dob_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:patient.Patient)
    }

    // @@protoc_insertion_point(class_scope:patient.Patient)
    private static final com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient();
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Patient>
        PARSER = new com.google.protobuf.AbstractParser<Patient>() {
      @java.lang.Override
      public Patient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Patient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Patient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patient.PatientRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();
  }
  /**
   * Protobuf type {@code patient.PatientRequest}
   */
  public static final class PatientRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:patient.PatientRequest)
      PatientRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "PatientRequest");
    }
    // Use PatientRequest.newBuilder() to construct.
    private PatientRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PatientRequest() {
      uuid_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.class, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uuid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest)) {
        return super.equals(obj);
      }
      com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest other = (com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patient.PatientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patient.PatientRequest)
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.class, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.Builder.class);
      }

      // Construct using com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uuid_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientRequest_descriptor;
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest getDefaultInstanceForType() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest build() {
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest buildPartial() {
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest result = new com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uuid_ = uuid_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest) {
          return mergeFrom((com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest other) {
        if (other == com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:patient.PatientRequest)
    }

    // @@protoc_insertion_point(class_scope:patient.PatientRequest)
    private static final com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest();
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientRequest>
        PARSER = new com.google.protobuf.AbstractParser<PatientRequest>() {
      @java.lang.Override
      public PatientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PatientRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PatientResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patient.PatientResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    java.util.List<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient> 
        getPatientsList();
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient getPatients(int index);
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    int getPatientsCount();
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    java.util.List<? extends com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder> 
        getPatientsOrBuilderList();
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder getPatientsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code patient.PatientResponse}
   */
  public static final class PatientResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:patient.PatientResponse)
      PatientResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "PatientResponse");
    }
    // Use PatientResponse.newBuilder() to construct.
    private PatientResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PatientResponse() {
      patients_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.class, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.Builder.class);
    }

    public static final int PATIENTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient> patients_;
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient> getPatientsList() {
      return patients_;
    }
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder> 
        getPatientsOrBuilderList() {
      return patients_;
    }
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    @java.lang.Override
    public int getPatientsCount() {
      return patients_.size();
    }
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    @java.lang.Override
    public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient getPatients(int index) {
      return patients_.get(index);
    }
    /**
     * <code>repeated .patient.Patient patients = 1;</code>
     */
    @java.lang.Override
    public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder getPatientsOrBuilder(
        int index) {
      return patients_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < patients_.size(); i++) {
        output.writeMessage(1, patients_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;

          {
            final int count = patients_.size();
            for (int i = 0; i < count; i++) {
              size += com.google.protobuf.CodedOutputStream
                .computeMessageSizeNoTag(patients_.get(i));
            }
            size += 1 * count;
          }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse)) {
        return super.equals(obj);
      }
      com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse other = (com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse) obj;

      if (!getPatientsList()
          .equals(other.getPatientsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPatientsCount() > 0) {
        hash = (37 * hash) + PATIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getPatientsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patient.PatientResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patient.PatientResponse)
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.class, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.Builder.class);
      }

      // Construct using com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (patientsBuilder_ == null) {
          patients_ = java.util.Collections.emptyList();
        } else {
          patients_ = null;
          patientsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.internal_static_patient_PatientResponse_descriptor;
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse getDefaultInstanceForType() {
        return com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse build() {
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse buildPartial() {
        com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse result = new com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse result) {
        if (patientsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            patients_ = java.util.Collections.unmodifiableList(patients_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.patients_ = patients_;
        } else {
          result.patients_ = patientsBuilder_.build();
        }
      }

      private void buildPartial0(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse) {
          return mergeFrom((com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse other) {
        if (other == com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse.getDefaultInstance()) return this;
        if (patientsBuilder_ == null) {
          if (!other.patients_.isEmpty()) {
            if (patients_.isEmpty()) {
              patients_ = other.patients_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePatientsIsMutable();
              patients_.addAll(other.patients_);
            }
            onChanged();
          }
        } else {
          if (!other.patients_.isEmpty()) {
            if (patientsBuilder_.isEmpty()) {
              patientsBuilder_.dispose();
              patientsBuilder_ = null;
              patients_ = other.patients_;
              bitField0_ = (bitField0_ & ~0x00000001);
              patientsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetPatientsFieldBuilder() : null;
            } else {
              patientsBuilder_.addAllMessages(other.patients_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient m =
                    input.readMessage(
                        com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.parser(),
                        extensionRegistry);
                if (patientsBuilder_ == null) {
                  ensurePatientsIsMutable();
                  patients_.add(m);
                } else {
                  patientsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient> patients_ =
        java.util.Collections.emptyList();
      private void ensurePatientsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          patients_ = new java.util.ArrayList<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient>(patients_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder> patientsBuilder_;

      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public java.util.List<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient> getPatientsList() {
        if (patientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(patients_);
        } else {
          return patientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public int getPatientsCount() {
        if (patientsBuilder_ == null) {
          return patients_.size();
        } else {
          return patientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient getPatients(int index) {
        if (patientsBuilder_ == null) {
          return patients_.get(index);
        } else {
          return patientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder setPatients(
          int index, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient value) {
        if (patientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientsIsMutable();
          patients_.set(index, value);
          onChanged();
        } else {
          patientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder setPatients(
          int index, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder builderForValue) {
        if (patientsBuilder_ == null) {
          ensurePatientsIsMutable();
          patients_.set(index, builderForValue.build());
          onChanged();
        } else {
          patientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder addPatients(com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient value) {
        if (patientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientsIsMutable();
          patients_.add(value);
          onChanged();
        } else {
          patientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder addPatients(
          int index, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient value) {
        if (patientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePatientsIsMutable();
          patients_.add(index, value);
          onChanged();
        } else {
          patientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder addPatients(
          com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder builderForValue) {
        if (patientsBuilder_ == null) {
          ensurePatientsIsMutable();
          patients_.add(builderForValue.build());
          onChanged();
        } else {
          patientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder addPatients(
          int index, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder builderForValue) {
        if (patientsBuilder_ == null) {
          ensurePatientsIsMutable();
          patients_.add(index, builderForValue.build());
          onChanged();
        } else {
          patientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder addAllPatients(
          java.lang.Iterable<? extends com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient> values) {
        if (patientsBuilder_ == null) {
          ensurePatientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, patients_);
          onChanged();
        } else {
          patientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder clearPatients() {
        if (patientsBuilder_ == null) {
          patients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          patientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public Builder removePatients(int index) {
        if (patientsBuilder_ == null) {
          ensurePatientsIsMutable();
          patients_.remove(index);
          onChanged();
        } else {
          patientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder getPatientsBuilder(
          int index) {
        return internalGetPatientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder getPatientsOrBuilder(
          int index) {
        if (patientsBuilder_ == null) {
          return patients_.get(index);  } else {
          return patientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public java.util.List<? extends com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder> 
           getPatientsOrBuilderList() {
        if (patientsBuilder_ != null) {
          return patientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(patients_);
        }
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder addPatientsBuilder() {
        return internalGetPatientsFieldBuilder().addBuilder(
            com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.getDefaultInstance());
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder addPatientsBuilder(
          int index) {
        return internalGetPatientsFieldBuilder().addBuilder(
            index, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.getDefaultInstance());
      }
      /**
       * <code>repeated .patient.Patient patients = 1;</code>
       */
      public java.util.List<com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder> 
           getPatientsBuilderList() {
        return internalGetPatientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder> 
          internalGetPatientsFieldBuilder() {
        if (patientsBuilder_ == null) {
          patientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient, com.kenyajug.encounter.grpc.patient.PatientOuterClass.Patient.Builder, com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientOrBuilder>(
                  patients_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          patients_ = null;
        }
        return patientsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:patient.PatientResponse)
    }

    // @@protoc_insertion_point(class_scope:patient.PatientResponse)
    private static final com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse();
    }

    public static com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PatientResponse>
        PARSER = new com.google.protobuf.AbstractParser<PatientResponse>() {
      @java.lang.Override
      public PatientResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PatientResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PatientResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kenyajug.encounter.grpc.patient.PatientOuterClass.PatientResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patient_Patient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_patient_Patient_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patient_PatientRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_patient_PatientRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patient_PatientResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_patient_PatientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpatient.proto\022\007patient\"2\n\007Patient\022\014\n\004u" +
      "uid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003dob\030\003 \001(\t\"\036\n\016" +
      "PatientRequest\022\014\n\004uuid\030\001 \001(\t\"5\n\017PatientR" +
      "esponse\022\"\n\010patients\030\001 \003(\0132\020.patient.Pati" +
      "ent2X\n\016PatientService\022F\n\021FindPatientByUu" +
      "id\022\027.patient.PatientRequest\032\030.patient.Pa" +
      "tientResponseB%\n#com.kenyajug.encounter." +
      "grpc.patientb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_patient_Patient_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_patient_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_patient_Patient_descriptor,
        new java.lang.String[] { "Uuid", "Name", "Dob", });
    internal_static_patient_PatientRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_patient_PatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_patient_PatientRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_patient_PatientResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_patient_PatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_patient_PatientResponse_descriptor,
        new java.lang.String[] { "Patients", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
